### ISSUE TITLE
Issue trying to auth

### ISSUE THREAD

**Issue by BassTeQ** [akhan23wgu/amazon-alexa-lg-tv#12]
I'm getting the error below when trying to auth, using python v2.7.
TV is connected via cable not wifi.
If use a web browser an go to http://192.168.100.6:3000 I see the "Hello World" page.

```
brad@linux-vm ~/Documents/amazon-alexa-lg-tv $ python lgtv.py auth 192.168.100.6
Traceback (most recent call last):
  File "lgtv.py", line 480, in <module>
    ws.connect()
  File "/usr/local/lib/python2.7/dist-packages/ws4py/client/__init__.py", line 217, in connect
    self.sock.connect(self.bind_addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

```
Any ideas?

Thanks

**Comment by akhan23wgu** [comment]
Can you ping and telnet into 192.168.100.6?

**Comment by BassTeQ** [comment]
I'm able to successfully PING that IP, but can't telnet.

**Comment by BassTeQ** [comment]
Any ideas? I tried telnet/ssh on ports 22/23, is telnet listening on a different port?

Nmap scan report for LGWEBOSTV (192.168.100.6)
Host is up (1.00s latency).
Not shown: 992 closed ports
PORT     STATE    SERVICE
514/tcp  filtered shell
1037/tcp filtered ams
1108/tcp open     ratio-adp
2001/tcp open     dc
3000/tcp open     ppp
3001/tcp open     nessus
9080/tcp open     glrpc
9998/tcp open     distinct32

**Comment by akhan23wgu** [comment]
My results are below.  What model and what version of WebOS? I have a 60UH6150.

![image](https://user-images.githubusercontent.com/16216291/35373024-06f23884-015a-11e8-852b-9a94f0cef72f.png)

**Comment by BassTeQ** [comment]
> My results are below. What model and what version of WebOS? I have a 60UH6150.

I'll check and get back to you.

**Comment by BassTeQ** [comment]
I have WebOS 4.70.06

**Comment by 50l3r** [comment]
+1 I cant auth
