### ISSUE TITLE
Problem with auth

### ISSUE THREAD

**Issue by 50l3r** [akhan23wgu/amazon-alexa-lg-tv#19]
I recieve this error when i try to auth

```
root@osboxes:/home/osboxes/amazon-alexa-lg-tv# python lgtv.py auth 192.168.1.20
Traceback (most recent call last):
  File "lgtv.py", line 479, in <module>
    ws = LGTVClient(sys.argv[2])
  File "lgtv.py", line 210, in __init__
    self.__macAddress = getMacAddress(self.__ip)
  File "lgtv.py", line 154, in getMacAddress
    pid = subprocess.Popen(["arp", "-n", address], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
```

I activate mobile tv and http://192.168.1.20:3000/ returns "hello world"

**Comment by BassTeQ** [comment]
I raised this same issue back in Dec last year, no reply or help, looks like the author has abandoned this project :(

**Comment by BassTeQ** [comment]
I managed to finally get this working!
