### ISSUE TITLE
Errno 11001 getaddreinfo failed

### ISSUE THREAD

**Issue by sphirst** [akhan23wgu/amazon-alexa-lg-tv#5]
Get the following problem when putting "python lgtv.py auth [http://192.168.1.83]"

Traceback (most recent call last):
  File "lgtv.py", line 479, in <module>
    ws = LGTVClient(sys.argv[2])
  File "lgtv.py", line 209, in __init__
    self.__ip = resolveHost(hostname)
  File "lgtv.py", line 150, in resolveHost
    return socket.gethostbyname(hostname)
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by akhan23wgu** [comment]
Use "python lgtv.py auth 192.168.1.83"
